### PR TITLE
Do not catch errors thrown in callback

### PR DESCRIPTION
**Pull request by charlierudolph**
@jden

### CODE REVIEW

**Comment by junosuarez** [comment]
I'm not sure what this change accomplishes. Could you describe it further?

**Comment by charlierudolph** [comment]
Since you are executing the callback inside the try block, you will also catch errors thrown in the callback.
Thus if the callback throws an error then the callback will be called a second time with that error. This is unexpected as the `asyncify` is only suppose to catch errors thrown by the syncFn.

**Comment by charlierudolph** [comment]
@jden bump.

**Comment by charlierudolph** [comment]
@jden please review, otherwise I'm just going to close this

**Comment by junosuarez** [comment]
You're quite correct- a node callback should only be called exactly once.
[sorry for the delay, and thanks for the PR & the explanation]

**Comment by junosuarez** [comment]
Published on npm as node-asyncify@0.2.1

**Pull request merged**
